### ISSUE TITLE
Using JPA to Create and Access a Database

### ISSUE THREAD

**Issue by fabgrel10** [fabgrel10/cardatabase-backend#1]
<div align="center">

Type | About | Labels
---|---|---
Feature ✨  | JPA | Enhancement

</div>

## Context
Use Java Persistent API (JPA) with Spring Boot and define a database by using entity classes.

## Tasks

- [ ] Create the entity classes.
- [ ] Create CRUD repositories
- [ ] Add relationships between tables.
- [ ] Set up the database.
